name: Run Python App

on:
  workflow_dispatch:

jobs:
  run-python-app:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install dependencies (if any)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      # Step 4: Run the Python script
      - name: Run Python Application
        run: |
          python app.py
