name: Run Python App (Dropdown)

on:
  workflow_dispatch:
    inputs:
      operation:
        description: "Choose an operation to perform"
        required: true
        type: choice
        options:
          - Option 1: Run App
          - Option 2: Install Dependencies Only

jobs:
  run-python-app:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Conditional Steps Based on Selection
      - name: Perform Selected Operation
        run: |
          if [ "${{ github.event.inputs.operation }}" = "Option 1: Run App" ]; then
            echo "Running the Python Application..."
            python -m pip install --upgrade pip
            python app.py
          elif [ "${{ github.event.inputs.operation }}" = "Option 2: Install Dependencies Only" ]; then
            echo "Installing dependencies only..."
            python -m pip install --upgrade pip
          fi
